### ISSUE TITLE
Doesn't work at all

### ISSUE THREAD

**Issue by probil** [fliphub/d-l-l#12]
webpack 3.5.2, default auto config

I got an error while building:
```
> webpack --config webpack.config.development.js

⏲  d-l-l took: 54.687ms
ModuleNotFoundError: Module not found: Error: Can't resolve 'child_process' in '/home/maks/Projects/ba-site/public/node_modules/execa'
    at factoryCallback (/home/maks/Projects/ba-site/public/node_modules/webpack/lib/Compilation.js:264:39)
    at factory (/home/maks/Projects/ba-site/public/node_modules/webpack/lib/NormalModuleFactory.js:235:20)
    at resolver (/home/maks/Projects/ba-site/public/node_modules/webpack/lib/NormalModuleFactory.js:60:20)
    at asyncLib.parallel (/home/maks/Projects/ba-site/public/node_modules/webpack/lib/NormalModuleFactory.js:127:20)
    at /home/maks/Projects/ba-site/public/node_modules/async/dist/async.js:3861:9
    at /home/maks/Projects/ba-site/public/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/home/maks/Projects/ba-site/public/node_modules/async/dist/async.js:996:13)
    at /home/maks/Projects/ba-site/public/node_modules/async/dist/async.js:906:16
    at /home/maks/Projects/ba-site/public/node_modules/async/dist/async.js:3858:13
    at resolvers.normal.resolve (/home/maks/Projects/ba-site/public/node_modules/webpack/lib/NormalModuleFactory.js:119:22)
    at onError (/home/maks/Projects/ba-site/public/node_modules/enhanced-resolve/lib/Resolver.js:65:10)
    at loggingCallbackWrapper (/home/maks/Projects/ba-site/public/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at runAfter (/home/maks/Projects/ba-site/public/node_modules/enhanced-resolve/lib/Resolver.js:158:4)
    at innerCallback (/home/maks/Projects/ba-site/public/node_modules/enhanced-resolve/lib/Resolver.js:146:3)
    at loggingCallbackWrapper (/home/maks/Projects/ba-site/public/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/home/maks/Projects/ba-site/public/node_modules/tapable/lib/Tapable.js:252:11)
    at /home/maks/Projects/ba-site/public/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:40:4
    at loggingCallbackWrapper (/home/maks/Projects/ba-site/public/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at runAfter (/home/maks/Projects/ba-site/public/node_modules/enhanced-resolve/lib/Resolver.js:158:4)
    at innerCallback (/home/maks/Projects/ba-site/public/node_modules/enhanced-resolve/lib/Resolver.js:146:3)
    at loggingCallbackWrapper (/home/maks/Projects/ba-site/public/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/home/maks/Projects/ba-site/public/node_modules/tapable/lib/Tapable.js:252:11)
    at innerCallback (/home/maks/Projects/ba-site/public/node_modules/enhanced-resolve/lib/Resolver.js:144:11)
    at loggingCallbackWrapper (/home/maks/Projects/ba-site/public/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/home/maks/Projects/ba-site/public/node_modules/tapable/lib/Tapable.js:249:35)
    at resolver.doResolve.createInnerCallback (/home/maks/Projects/ba-site/public/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:44:6)
    at loggingCallbackWrapper (/home/maks/Projects/ba-site/public/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at afterInnerCallback (/home/maks/Projects/ba-site/public/node_modules/enhanced-resolve/lib/Resolver.js:166:11)
    at loggingCallbackWrapper (/home/maks/Projects/ba-site/public/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/home/maks/Projects/ba-site/public/node_modules/tapable/lib/Tapable.js:249:35)
resolve 'child_process' in '/home/maks/Projects/ba-site/public/node_modules/execa'
  Parsed request is a module
  using description file: /home/maks/Projects/ba-site/public/node_modules/execa/package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /home/maks/Projects/ba-site/public/node_modules/execa/package.json (relative path: .)
    resolve as module
      /home/maks/Projects/ba-site/public/node_modules/execa/node_modules doesn't exist or is not a directory
      /home/maks/Projects/ba-site/public/node_modules/node_modules doesn't exist or is not a directory
      /home/maks/Projects/node_modules doesn't exist or is not a directory
      /home/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /home/maks/Projects/ba-site/public/node_modules
        using description file: /home/maks/Projects/ba-site/public/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /home/maks/Projects/ba-site/public/package.json (relative path: ./node_modules)
          using description file: /home/maks/Projects/ba-site/public/package.json (relative path: ./node_modules/child_process)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /home/maks/Projects/ba-site/public/node_modules/child_process doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /home/maks/Projects/ba-site/public/node_modules/child_process.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /home/maks/Projects/ba-site/public/node_modules/child_process.json doesn't exist
            as directory
              /home/maks/Projects/ba-site/public/node_modules/child_process doesn't exist
      looking for modules in /home/maks/Projects/ba-site/node_modules
        using description file: /home/maks/Projects/ba-site/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /home/maks/Projects/ba-site/package.json (relative path: ./node_modules)
          using description file: /home/maks/Projects/ba-site/package.json (relative path: ./node_modules/child_process)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /home/maks/Projects/ba-site/node_modules/child_process doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /home/maks/Projects/ba-site/node_modules/child_process.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /home/maks/Projects/ba-site/node_modules/child_process.json doesn't exist
            as directory
              /home/maks/Projects/ba-site/node_modules/child_process doesn't exist
      looking for modules in /home/maks/node_modules
        No description file found
        Field 'browser' doesn't contain a valid alias configuration
        No description file found
        no extension
          Field 'browser' doesn't contain a valid alias configuration
          /home/maks/node_modules/child_process doesn't exist
        .js
          Field 'browser' doesn't contain a valid alias configuration
          /home/maks/node_modules/child_process.js doesn't exist
        .json
          Field 'browser' doesn't contain a valid alias configuration
          /home/maks/node_modules/child_process.json doesn't exist
        as directory
          /home/maks/node_modules/child_process doesn't exist

```

**Comment by waterfoul** [comment]
What version of node are you running? child_process should be a built in module

**Comment by probil** [comment]
```
node: 8.3.0
npm: 5.3.0
os: archlinux
```

**Comment by aretecode** [comment]
@probil wasn't watching this repo I will push a refactor soon
